zephyr-7b-beta:
  prompt_template: /home/zhanw0g/github/lm-evaluation-harness/alpaca/zephyr-7b-beta/prompt.txt
  fn_completions: "huggingface_local_completions"
  completions_kwargs:
    model_name: "HuggingFaceH4/zephyr-7b-beta"
    model_kwargs:
      torch_dtype: 'float16'
    max_new_tokens: 2048
    top_p: 1.0
    temperature: 0.7
    do_sample: True



  pretty_name: "Zephyr 7B Î²"
  link: "https://huggingface.co/HuggingFaceH4/zephyr-7b-beta"
