beaver-7b-v1.0:
  prompt_template: /home/zhanw0g/github/lm-evaluation-harness/alpaca/beaver-7b-v1.0/prompt.txt
  fn_completions: "huggingface_local_completions"
  completions_kwargs:
    model_name: "PKU-Alignment/beaver-7b-v1.0"
    model_kwargs:
      torch_dtype: 'float16'
    max_new_tokens: 2048
    temperature: 1.0




  pretty_name: "Beaver 7B v1.0"
  link: "https://github.com/PKU-Alignment/safe-rlhf/tree/main"
