mistral-7b-v13:
  prompt_template: /home/zhanw0g/github/lm-evaluation-harness/alpaca/mistral-7b-v13/prompt.txt
  fn_completions: "huggingface_local_completions"
  completions_kwargs:
    model_name: "OpenBuddy/openbuddy-mistral-7b-v13" 
    model_kwargs:
      torch_dtype: 'float16'
    max_new_tokens: 2048 #check
    temperature: 1.0




  pretty_name: "Mistral 7B v13"
  link: https://huggingface.co/OpenBuddy/openbuddy-mistral-7b-v13
