juanako-7b-UNA:
  prompt_template: /home/zhanw0g/github/lm-evaluation-harness/alpaca/juanako-7b-UNA/prompt.txt
  fn_completions: "huggingface_local_completions"
  completions_kwargs:
    model_name: "fblgit/juanako-7b-UNA"
    model_kwargs:
      torch_dtype: 'float16'
    max_new_tokens: 2048 #check
    temperature: 1.0




  pretty_name: "juanako 7B Uniform Neural Alignment"
  link: "https://huggingface.co/fblgit/juanako-7b-UNA"
