openchat-v3.5-7b:
  prompt_template: "/home/zhanw0g/github/lm-evaluation-harness/alpaca/openchat-v3.5-7b/prompt.txt"
  fn_completions: "huggingface_local_completions"
  completions_kwargs:
    model_name: "openchat/openchat_3.5"
    model_kwargs:
      torch_dtype: 'float16'
    max_new_tokens: 2048
    top_p: 1.0
    temperature: 0.7
    do_sample: True



  pretty_name: "OpenChat V3.5 7B"
  link: "https://github.com/imoneoi/openchat"
